/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LenataHoma
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        tableDark1.fixTable(jScrollPane2);
        tableDark1.setColumnAlignment(0, JLabel.CENTER);
        tableDark1.setCellAlignment(0, JLabel.CENTER);
        tableDark1.setColumnAlignment(2, JLabel.CENTER);
        tableDark1.setCellAlignment(2, JLabel.CENTER);
        tableDark1.setColumnAlignment(4, JLabel.RIGHT);
        tableDark1.setCellAlignment(4, JLabel.RIGHT);
        tableDark1.setColumnWidth(0, 50);
        tableDark1.setColumnWidth(2, 100);
        DefaultTableModel mode = (DefaultTableModel) tableDark1.getModel();
//        for (int i = 0; i <= 20; i++) {
//            mode.addRow(new Object[]{i, "Ra Ven", 10, "001 001 001", "PP"});
//        }
        loadTable();
    }

    public void loadTable(){
        DefaultTableModel modem = new DefaultTableModel();
        modem.addColumn("A");
        modem.addColumn("B");
        modem.addColumn("C");
        tableDark1.setModel(modem);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TanggalTransaksi = new Swing.TextField();
        IDTransaksi1 = new Swing.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDark1 = new Swing.TableDark();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(957, 544));
        setMinimumSize(new java.awt.Dimension(957, 544));
        setPreferredSize(new java.awt.Dimension(957, 544));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TanggalTransaksi.setLabelText("Tanggal Transaksi");
        getContentPane().add(TanggalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 300, -1));

        IDTransaksi1.setLabelText("ID Transaksi");
        getContentPane().add(IDTransaksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 300, -1));

        tableDark1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDark1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 620, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.TextField IDTransaksi1;
    private Swing.TextField TanggalTransaksi;
    private javax.swing.JScrollPane jScrollPane2;
    private Swing.TableDark tableDark1;
    // End of variables declaration//GEN-END:variables
}
